# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - whatsapp-bailey(routes)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://whatsappcontainer.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_6c4cd801569942d48e3338624f86e700 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_d3ed38ab00274f23bdafb526f91498ce }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: whatsappcontainer.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_6c4cd801569942d48e3338624f86e700 }}/whatsapp-api-nodejs-main:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'routes'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'whatsapp-bailey'
        slot-name: 'routes'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_d9d3fd1713af41b1b21a6385ae2c220f }}
        images: 'whatsappcontainer.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_6c4cd801569942d48e3338624f86e700 }}/whatsapp-api-nodejs-main:${{ github.sha }}'